server:
  port: 7000
spring:
  application:
    name: LOCK-WEBUI
  redis:
    host: 192.168.204.129
    port: 6379
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true